version: '2'

services:
  app:
    image: 'partner-challenge:latest'
    ports:
          - 8889:8080
    build:
      context: .
    container_name: partner-challenge
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/partners
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

          
  db:
    image: 'postgres:11'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_NAME=partners
      - APP_DB_USER=postgres
      - APP_DB_PASS=admin

    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: