spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/partners
    username: postgres
    password: admin
    hikari:
      pool-name: partners-pool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
server:
  compression:
    enabled: true

